/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedCotacaoRouteImport } from './routes/_authenticated/cotacao'

const AuthenticatedCotacaoRoute = AuthenticatedCotacaoRouteImport.update({
  id: '/_authenticated/cotacao',
  path: '/cotacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cotacao': typeof AuthenticatedCotacaoRoute
}
export interface FileRoutesByTo {
  '/cotacao': typeof AuthenticatedCotacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/cotacao': typeof AuthenticatedCotacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cotacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/cotacao'
  id: '__root__' | '/_authenticated/cotacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCotacaoRoute: typeof AuthenticatedCotacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/cotacao': {
      id: '/_authenticated/cotacao'
      path: '/cotacao'
      fullPath: '/cotacao'
      preLoaderRoute: typeof AuthenticatedCotacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCotacaoRoute: AuthenticatedCotacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
